/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agenda.view;

import br.com.agenda.dominio.Contato;
import br.com.agenda.negocio.Negocio;
import br.com.agenda.negocio.Principal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alunos
 */
public class ListaDeContatos extends javax.swing.JPanel {

    /**
     * Creates new form ListaDeContatos
     */
    public ListaDeContatos() {
        initComponents();
        List<Contato> contatos = Negocio.pesquisar("");
        adicionarListaContatosTabela(contatos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        retornoTabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfCampoDeBusca = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();
        bAlterar = new javax.swing.JButton();
        bNovo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 300));

        retornoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        retornoTabela.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(retornoTabela);
        retornoTabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(jScrollPane1, gridBagConstraints);

        jLabel2.setText("Busca");
        jPanel1.add(jLabel2);

        tfCampoDeBusca.setMinimumSize(new java.awt.Dimension(100, 20));
        tfCampoDeBusca.setPreferredSize(new java.awt.Dimension(100, 20));
        tfCampoDeBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampoDeBuscaActionPerformed(evt);
            }
        });
        jPanel1.add(tfCampoDeBusca);

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(bBuscar);

        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(bExcluir);

        bAlterar.setText("Alterar");
        bAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(bAlterar);

        bNovo.setText("Novo");
        bNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoActionPerformed(evt);
            }
        });
        jPanel1.add(bNovo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(jPanel1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Contato");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void bNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoActionPerformed
        Principal.adicionarNovo();
    }//GEN-LAST:event_bNovoActionPerformed

    private void tfCampoDeBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoDeBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampoDeBuscaActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        List<Contato> contatos = Negocio.pesquisar(tfCampoDeBusca.getText());
        adicionarListaContatosTabela(contatos);
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        int linha = retornoTabela.getSelectedRow();
        if (linha >= 0) {
            String idContato = (String) retornoTabela.getValueAt(linha, 0);
            System.out.println("ID: " + idContato);
            boolean apagou = Negocio.exluir(Integer.valueOf(idContato));
            if (apagou) {
                JOptionPane.showMessageDialog(this, "Apagado com sucesso");
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possivel apagar");
            }
            bBuscarActionPerformed(null);
        }
    }//GEN-LAST:event_bExcluirActionPerformed

    private void bAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarActionPerformed
        Contato c = new Contato();
        int linha = retornoTabela.getSelectedRow();
        if (linha >= 0) {
            String id =  (String)retornoTabela.getValueAt(linha, 0);
            c.setId(Integer.valueOf(id));
            c.setNome((String) retornoTabela.getValueAt(linha, 1));
            c.setCpf((String) retornoTabela.getValueAt(linha, 2));
            c.setEmail((String) retornoTabela.getValueAt(linha, 3));
        }

        Principal.alterar(c);


    }//GEN-LAST:event_bAlterarActionPerformed

    public void adicionarListaContatosTabela(List<Contato> list) {
        String[] colunas = {"Codigo", "Nome", "CPF", "Email"};
        String[][] dados = new String[list.size()][colunas.length];
        for (int i = 0; i < list.size(); i++) {
            Contato c = list.get(i);
            dados[i][0] = c.getId() == null ? "" + i : c.getId().toString();
            dados[i][1] = c.getNome() == null ? " " : c.getNome();
            dados[i][2] = c.getCpf() == null ? "000.000.000-00" : c.getCpf();
            dados[i][3] = c.getEmail() == null ? "seuemail@gmail.com" : c.getEmail();
        }
        DefaultTableModel modelo = new DefaultTableModel(dados, colunas);
        retornoTabela.setModel(modelo);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlterar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable retornoTabela;
    private javax.swing.JTextField tfCampoDeBusca;
    // End of variables declaration//GEN-END:variables
}
